### PR TITLE
Rebase 8.3 patches onto v10.10.16

### PR DESCRIPTION
**Pull request by ydirson**

### CODE REVIEW

**Comment by ydirson** [comment]
In current state I did not rebase any of our branches
- `restore-multipath-conf` will need to get squashed
- `lvm-vs-ext` required textually-heavy (but not that difficult) conflict resolution and would benefit from a rebase onto more recent upstream release
- the other branches did show a few simple conflicts only

**Comment by stormi** [comment]
Any advice on how to review this?

**Comment by ydirson** [comment]
> Any advice on how to review this?

Since the individual branches did not change yet, I would suggest to focus on merge commits. `gitk xcpng/10.10.16-8.3...xcpng/ydi/10.10.16-8.3` is likely a good tool (or maybe `tig` for those more used to that tool)

**Comment by stormi** [comment]
So, I tried it but quickly got lost when trying to understand the meaning of some of the diffs of diffs. I'll probably be more efficient after a quick screen share.

**Comment by stormi** [comment]
We reviewed the diffs of diffs together with Yann. Good for me. @benjamreis I believe you can skip the review if you want. Yann will just rebase something before the merge.

**Review by stormi — APPROVED** [review]

**Review by benjamreis — APPROVED** [review]
LGTM

**Comment by ydirson** [comment]
rerolled 2 sub-branches:
- restore-multipath-conf: squash the fixup into its parent
- lvm-vs-ext:
  - rebased onto v10.10.16 for better readability after upstream UI change
  - squashed the wording change together with the checkbox -> radiobar change

**Comment by ydirson** [comment]
... and fixed authorship of rewritten commit for DCO check to pass

**Pull request merged**
