### PR TITLE
LVM/EXT radiobuttons

### PR DESCRIPTION
**Pull request by ydirson**
radio-buttons

### CODE REVIEW

**Comment by stormi** [comment]
Could you add a screenshot of the resulting screen?

**Comment by stormi** [comment]
To make things clear and separate both groups of choices, let's add a title or question just before the radiobuttons. Simply "Storage type:".

**Comment by ydirson** [comment]
> To make things clear and separate both groups of choices, let's add a title or question just before the radiobuttons. Simply "Storage type:".

updated

**Review by stormi — APPROVED** [review]

**Comment by stormi** [comment]
Current result: 
image

**Review by benjamreis — APPROVED** [review]

**Pull request merged**
