### PR TITLE
Rebase of simple 8.2.1 patches onto 8.3 codebase

### PR DESCRIPTION
**Pull request by ydirson**
This "simple patches" criteria leaves out:
- gpgcheck handling (support added upstream, but without user toggles)
- retry install on network/gpgcheck error

### CODE REVIEW

**Comment by stormi** [comment]
Looks like several commits are missing a DCO.

**Review by benjamreis — APPROVED** [review]
LGTM
I guess each relevant commits would be a fine upsream PR, small enough etc.

**Comment by stormi** [comment]
I haven't had time to review it entirely yet, but the first commit I reviewed has a wrong commit message: "This commit is the version that the initial installer for XCP-ng 7.5.0 had." is not true anymore, and only applied to the first of the two commits that were squashed together to create the new commit. I suggest simply removing this sentence. 

My other comment on the same commit is I expected the original commits to be referenced in the commit message. This might apply to the other commits that I haven't reviewed yet, too.

**Comment by ydirson** [comment]
Added `Orig-commit:` links to all commit messages that did not have one (the first one was the only squash commit missing one)

**Review by stormi — APPROVED** [review]

**Review by Wescoeur — APPROVED** [review]

**Pull request merged**
