### PR TITLE
Rebase on v10.10.8 for 8.3

### PR DESCRIPTION
**Pull request by ydirson**
This is a rebase of branch 10.10.5-8.3 as of 248f58b043517d3f0648f72deeeb3fc4dacd94f8.

A few interactions between the new "get NTP servers from DHCP" feature and IPv6 patches might need detailed review of the ipv6 part of the rebase.

### CODE REVIEW

**Review by benjamreis — APPROVED** [review]

**Comment by stormi** [comment]
Nothing to adapt regarding IPv6 handling and NTP, @benjamreis?

**Review by stormi — APPROVED** [review]
I let you all validate / push the branch, without reviewing the diffs myself. I'll just review the packaging side.

**Comment by benjamreis** [comment]
> Nothing to adapt regarding IPv6 handling and NTP, @benjamreis?

No NTP has the same behavior no matter the IP family

**Comment by ydirson** [comment]
Added upstream "fix" for the NTP crash, also included in `XenServer8_2023-08-22.iso`, hoping for a real upstream fix soon

**Comment by ydirson** [comment]
Redone the rebase:
- without rebasing each and every individual branch, to limit history noise
- uniting those older branches that got a few fixes to have only one merge each (and apply the fixup)

**Comment by ydirson** [comment]
Rebased onto upstream `xs8` tip, which includes 2 of the patches we previously applied:
- 905d716d307a8bdbe09171d7d8716f8ccc4d66e9
- 84557fdef45a43115733717fa7e5aaa46347575e

**Pull request merged**
